package com.eoddata.ws.data;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.9
 * Sat Jul 24 13:12:42 WST 2010
 * Generated source version: 2.2.9
 * 
 */
 
@WebService(targetNamespace = "http://ws.eoddata.com/Data", name = "DataSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface DataSoap {

    @WebResult(name = "QuoteGetResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "QuoteGet", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteGet")
    @WebMethod(operationName = "QuoteGet", action = "http://ws.eoddata.com/Data/QuoteGet")
    @ResponseWrapper(localName = "QuoteGetResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteGetResponse")
    public com.eoddata.ws.data.RESPONSE quoteGet(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    @WebResult(name = "SplitListByExchangeResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SplitListByExchange", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SplitListByExchange")
    @WebMethod(operationName = "SplitListByExchange", action = "http://ws.eoddata.com/Data/SplitListByExchange")
    @ResponseWrapper(localName = "SplitListByExchangeResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SplitListByExchangeResponse")
    public com.eoddata.ws.data.RESPONSE splitListByExchange(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "UpdateDataFormatResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "UpdateDataFormat", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.UpdateDataFormat")
    @WebMethod(operationName = "UpdateDataFormat", action = "http://ws.eoddata.com/Data/UpdateDataFormat")
    @ResponseWrapper(localName = "UpdateDataFormatResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.UpdateDataFormatResponse")
    public com.eoddata.ws.data.RESPONSE updateDataFormat(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "DataFormat", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String dataFormat,
        @WebParam(name = "IncludeHeader", targetNamespace = "http://ws.eoddata.com/Data")
        boolean includeHeader,
        @WebParam(name = "IncludeSuffix", targetNamespace = "http://ws.eoddata.com/Data")
        boolean includeSuffix
    );

    @WebResult(name = "Top10GainsResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "Top10Gains", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.Top10Gains")
    @WebMethod(operationName = "Top10Gains", action = "http://ws.eoddata.com/Data/Top10Gains")
    @ResponseWrapper(localName = "Top10GainsResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.Top10GainsResponse")
    public com.eoddata.ws.data.RESPONSE top10Gains(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "SymbolGetResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SymbolGet", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolGet")
    @WebMethod(operationName = "SymbolGet", action = "http://ws.eoddata.com/Data/SymbolGet")
    @ResponseWrapper(localName = "SymbolGetResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolGetResponse")
    public com.eoddata.ws.data.RESPONSE symbolGet(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    @WebResult(name = "ExchangeGetResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "ExchangeGet", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.ExchangeGet")
    @WebMethod(operationName = "ExchangeGet", action = "http://ws.eoddata.com/Data/ExchangeGet")
    @ResponseWrapper(localName = "ExchangeGetResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.ExchangeGetResponse")
    public com.eoddata.ws.data.RESPONSE exchangeGet(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "QuoteListByDateResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "QuoteListByDate", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteListByDate")
    @WebMethod(operationName = "QuoteListByDate", action = "http://ws.eoddata.com/Data/QuoteListByDate")
    @ResponseWrapper(localName = "QuoteListByDateResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteListByDateResponse")
    public com.eoddata.ws.data.RESPONSE quoteListByDate(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate
    );

    @WebResult(name = "ValidateAccessResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "ValidateAccess", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.ValidateAccess")
    @WebMethod(operationName = "ValidateAccess", action = "http://ws.eoddata.com/Data/ValidateAccess")
    @ResponseWrapper(localName = "ValidateAccessResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.ValidateAccessResponse")
    public com.eoddata.ws.data.RESPONSE validateAccess(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    @WebResult(name = "SymbolListResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SymbolList", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolList")
    @WebMethod(operationName = "SymbolList", action = "http://ws.eoddata.com/Data/SymbolList")
    @ResponseWrapper(localName = "SymbolListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolListResponse")
    public com.eoddata.ws.data.RESPONSE symbolList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "DataClientLatestVersionResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "DataClientLatestVersion", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.DataClientLatestVersion")
    @WebMethod(operationName = "DataClientLatestVersion", action = "http://ws.eoddata.com/Data/DataClientLatestVersion")
    @ResponseWrapper(localName = "DataClientLatestVersionResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.DataClientLatestVersionResponse")
    public com.eoddata.ws.data.RESPONSE dataClientLatestVersion(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    @WebResult(name = "QuoteList2Result", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "QuoteList2", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteList2")
    @WebMethod(operationName = "QuoteList2", action = "http://ws.eoddata.com/Data/QuoteList2")
    @ResponseWrapper(localName = "QuoteList2Response", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteList2Response")
    public com.eoddata.ws.data.RESPONSE quoteList2(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbols", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbols
    );

    @WebResult(name = "SymbolChartResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SymbolChart", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolChart")
    @WebMethod(operationName = "SymbolChart", action = "http://ws.eoddata.com/Data/SymbolChart")
    @ResponseWrapper(localName = "SymbolChartResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolChartResponse")
    public com.eoddata.ws.data.RESPONSE symbolChart(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    @WebResult(name = "FundamentalListResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "FundamentalList", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.FundamentalList")
    @WebMethod(operationName = "FundamentalList", action = "http://ws.eoddata.com/Data/FundamentalList")
    @ResponseWrapper(localName = "FundamentalListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.FundamentalListResponse")
    public com.eoddata.ws.data.RESPONSE fundamentalList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "QuoteListResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "QuoteList", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteList")
    @WebMethod(operationName = "QuoteList", action = "http://ws.eoddata.com/Data/QuoteList")
    @ResponseWrapper(localName = "QuoteListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteListResponse")
    public com.eoddata.ws.data.RESPONSE quoteList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "ExchangeMonthsResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "ExchangeMonths", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.ExchangeMonths")
    @WebMethod(operationName = "ExchangeMonths", action = "http://ws.eoddata.com/Data/ExchangeMonths")
    @ResponseWrapper(localName = "ExchangeMonthsResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.ExchangeMonthsResponse")
    public com.eoddata.ws.data.RESPONSE exchangeMonths(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "QuoteListByDatePeriodResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "QuoteListByDatePeriod", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteListByDatePeriod")
    @WebMethod(operationName = "QuoteListByDatePeriod", action = "http://ws.eoddata.com/Data/QuoteListByDatePeriod")
    @ResponseWrapper(localName = "QuoteListByDatePeriodResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.QuoteListByDatePeriodResponse")
    public com.eoddata.ws.data.RESPONSE quoteListByDatePeriod(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "QuoteDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String quoteDate,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    @WebResult(name = "SymbolHistoryPeriodResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SymbolHistoryPeriod", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolHistoryPeriod")
    @WebMethod(operationName = "SymbolHistoryPeriod", action = "http://ws.eoddata.com/Data/SymbolHistoryPeriod")
    @ResponseWrapper(localName = "SymbolHistoryPeriodResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolHistoryPeriodResponse")
    public com.eoddata.ws.data.RESPONSE symbolHistoryPeriod(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(name = "Date", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String date,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    @WebResult(name = "DataFormatsResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "DataFormats", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.DataFormats")
    @WebMethod(operationName = "DataFormats", action = "http://ws.eoddata.com/Data/DataFormats")
    @ResponseWrapper(localName = "DataFormatsResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.DataFormatsResponse")
    public com.eoddata.ws.data.RESPONSE dataFormats(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    @WebResult(name = "MembershipResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "Membership", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.Membership")
    @WebMethod(operationName = "Membership", action = "http://ws.eoddata.com/Data/Membership")
    @ResponseWrapper(localName = "MembershipResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.MembershipResponse")
    public com.eoddata.ws.data.RESPONSE membership(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    @WebResult(name = "ExchangeListResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "ExchangeList", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.ExchangeList")
    @WebMethod(operationName = "ExchangeList", action = "http://ws.eoddata.com/Data/ExchangeList")
    @ResponseWrapper(localName = "ExchangeListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.ExchangeListResponse")
    public com.eoddata.ws.data.RESPONSE exchangeList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    @WebResult(name = "SymbolChangesByExchangeResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SymbolChangesByExchange", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolChangesByExchange")
    @WebMethod(operationName = "SymbolChangesByExchange", action = "http://ws.eoddata.com/Data/SymbolChangesByExchange")
    @ResponseWrapper(localName = "SymbolChangesByExchangeResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolChangesByExchangeResponse")
    public com.eoddata.ws.data.RESPONSE symbolChangesByExchange(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "LoginResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "Login", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.Login")
    @WebMethod(operationName = "Login", action = "http://ws.eoddata.com/Data/Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.LoginResponse")
    public com.eoddata.ws.data.LOGINRESPONSE2 login(
        @WebParam(name = "Username", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String password
    );

    @WebResult(name = "CountryListResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "CountryList", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.CountryList")
    @WebMethod(operationName = "CountryList", action = "http://ws.eoddata.com/Data/CountryList")
    @ResponseWrapper(localName = "CountryListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.CountryListResponse")
    public com.eoddata.ws.data.RESPONSE countryList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token
    );

    @WebResult(name = "SymbolHistoryPeriodByDateRangeResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SymbolHistoryPeriodByDateRange", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolHistoryPeriodByDateRange")
    @WebMethod(operationName = "SymbolHistoryPeriodByDateRange", action = "http://ws.eoddata.com/Data/SymbolHistoryPeriodByDateRange")
    @ResponseWrapper(localName = "SymbolHistoryPeriodByDateRangeResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolHistoryPeriodByDateRangeResponse")
    public com.eoddata.ws.data.RESPONSE symbolHistoryPeriodByDateRange(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String endDate,
        @WebParam(name = "Period", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String period
    );

    @WebResult(name = "Top10LossesResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "Top10Losses", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.Top10Losses")
    @WebMethod(operationName = "Top10Losses", action = "http://ws.eoddata.com/Data/Top10Losses")
    @ResponseWrapper(localName = "Top10LossesResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.Top10LossesResponse")
    public com.eoddata.ws.data.RESPONSE top10Losses(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );

    @WebResult(name = "Login2Result", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "Login2", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.Login2")
    @WebMethod(operationName = "Login2", action = "http://ws.eoddata.com/Data/Login2")
    @ResponseWrapper(localName = "Login2Response", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.Login2Response")
    public com.eoddata.ws.data.LOGINRESPONSE2 login2(
        @WebParam(name = "Username", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String username,
        @WebParam(name = "Password", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String password,
        @WebParam(name = "Version", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String version
    );

    @WebResult(name = "SplitListBySymbolResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SplitListBySymbol", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SplitListBySymbol")
    @WebMethod(operationName = "SplitListBySymbol", action = "http://ws.eoddata.com/Data/SplitListBySymbol")
    @ResponseWrapper(localName = "SplitListBySymbolResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SplitListBySymbolResponse")
    public com.eoddata.ws.data.RESPONSE splitListBySymbol(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol
    );

    @WebResult(name = "SymbolHistoryResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "SymbolHistory", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolHistory")
    @WebMethod(operationName = "SymbolHistory", action = "http://ws.eoddata.com/Data/SymbolHistory")
    @ResponseWrapper(localName = "SymbolHistoryResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.SymbolHistoryResponse")
    public com.eoddata.ws.data.RESPONSE symbolHistory(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange,
        @WebParam(name = "Symbol", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String symbol,
        @WebParam(name = "StartDate", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String startDate
    );

    @WebResult(name = "TechnicalListResult", targetNamespace = "http://ws.eoddata.com/Data")
    @RequestWrapper(localName = "TechnicalList", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.TechnicalList")
    @WebMethod(operationName = "TechnicalList", action = "http://ws.eoddata.com/Data/TechnicalList")
    @ResponseWrapper(localName = "TechnicalListResponse", targetNamespace = "http://ws.eoddata.com/Data", className = "com.eoddata.ws.data.TechnicalListResponse")
    public com.eoddata.ws.data.RESPONSE technicalList(
        @WebParam(name = "Token", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String token,
        @WebParam(name = "Exchange", targetNamespace = "http://ws.eoddata.com/Data")
        java.lang.String exchange
    );
}
